spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:user_account_db}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-test.yaml