spring:
  application:
    name: user-acount-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_account_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret: ${JWT_SECRET:ваш-секретный-ключ-должен-быть-достаточно-длинным}

account:
  update:
    percent: ${ACCOUNT_UPDATE_PERCENT:10}
    max-balance: ${ACCOUNT_MAX_BALANCE:207}
logging:
  level:
    org:
      springframework:
        security: DEBUG
        transaction: TRACE
        orm:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE